### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by xpe-cd46** [Optimizory/vrest-desktop#1]
Hello,
I get an Internal Server Error trying to use vrest-ng Pro.
No problem with vrest-ng.
Had the same error with 0.7.1.
Thanks,

**Comment by dheerajaggarwal** [comment]
Hi,

Are you still facing the issue? If possible, please share a screenshot of the issue.

**Comment by xpe-cd46** [comment]
Hi,

yes, the issue is still the same. There is few to see:

[cid:image001.png@01D592F3.98E74820]



De : Dheeraj Aggarwal [mailto:notifications@github.com]
Envoyé : dimanche 27 octobre 2019 07:20
À : Optimizory/vrest-ng
Cc : PETARD Xavier; Author
Objet : Re: [Optimizory/vrest-ng] Internal Server Error (#1)


Hi,

Are you still facing the issue? If possible, please share a screenshot of the issue.

**Comment by dheerajaggarwal** [comment]
Hi,

Thank you for reporting this issue.

We are able to reproduce the issue. The issue occurred to us in case if we have not set any **Name** in our Github profile.

Now, we have removed this check. So just try to login now and you should be able to access vREST NG Pro now. We have recently launched v0.8.4. So I also recommend you to download the latest version and try out that version.

If the issue still persists then let us know a couple of date and time slots to setup a web meeting with you to resolve this issue quickly.

**Comment by xpe-cd46** [comment]
Hi,
issue solved!
Thanks a lot, I will now try the Pro version.

**Comment by dheerajaggarwal** [comment]
You are welcome :-) Feel free to contact us in case if you have any further queries/issues. You may also join our discord channel to get help instantaneously (Link [https://discord.gg/NtRa7kw](https://discord.gg/NtRa7kw)).

We are very close to stable version. So stay tuned with us.
