### ISSUE TITLE
Test execution gets stale forever

### ISSUE THREAD

**Issue by felixls** [Optimizory/vrest-desktop#2]
It works ok if I put the value `0.1` to `Wait for Seconds` test parameter.

**Comment by dheerajaggarwal** [comment]
Hi Sergio,

I am not able to reproduce the issue at my end. Will you be able to share the test case file with me to reproduce the issue?

And which version of vREST NG, are you using?

**Comment by felixls** [comment]
Hi,

I'm using version 1.1.0 on Arch Linux.

The test consist in a simple login process, make a POST to get authentication cookie:

```
{
  "details": {
    "summary": "Login",
    "description": "",
    "externalId": "",
    "condition": "",
    "loopSource": "",
    "waitForSeconds": "",
    "runnable": true
  },
  "validation": {
    "assertions": [
      {
        "source": "statusCode",
        "property": null,
        "operator": "equalToNumber",
        "expectedValue": "200"
      }
    ],
    "expectedBody": {
      "content": {},
      "type": "json"
    },
    "expectedSchema": {
      "content": {},
      "type": "json"
    }
  },
  "request": {
    "url": "http://test/login.json",
    "method": "POST",
    "headers": {},
    "queryParams": [],
    "body": {
      "content": {
        "username": "user",
        "email": "email@host.com",
        "password": "password",
        "rememberMe": false
      },
      "type": "json",
      "formParams": []
    }
  },
  "variables": [],
  "iterationResultVariable": "",
  "resultVariable": "",
  "extensions": {}
}
```

This first test never fails, but the second and after do (but is not deterministic).

Btw, this is happening with the sample suite also.

**Comment by dheerajaggarwal** [comment]
Hi Sergio, can we have a live chat or meeting to quickly resolve this issue?

Live Chat option is available on the bottom right corner of our website (https://ng.vrest.io).

**Comment by dheerajaggarwal** [comment]
Hi Sergio, 
Thanks for reporting this issue.
I am able to reproduce this issue on Linux. We will fix this issue soon and I will update you on this thread.

**Comment by felixls** [comment]
oh, great, sorry I'm busy these days, btw, I'm trying to introduce this to my employer I think will be a good fit for our test needs.

Thanks

**Comment by dheerajaggarwal** [comment]
Hi Sergio, 

We have fixed the issue at our end and we will be releasing the new build soon with in 1-2 days.

**Comment by dheerajaggarwal** [comment]
Hi Sergio,

We have released new version ([v1.2.0](https://ng.vrest.io/change-log)) of vREST NG Application which includes the fix of bug reported by you. We request you to try out the new version and let us know your feedback.

**Comment by felixls** [comment]
It worked like a charm!!

Thank you guys, now my tests are going at full speed without the delay.

**Comment by dheerajaggarwal** [comment]
Thanks Sergio for the quick update :-)
